### ISSUE TITLE
Can't chat to graphite (again)

### ISSUE THREAD

**Issue by chamoysans** [EvanZhouDev/graphite#3]
i swear it was working yesterday, until it just... stopped working entirely? i did try these tests but nothing worked for some reason:

- opened a new doc (completely empty with untitled name)
- new api key (made 3, nothing)
- waited a minute then tried again (still nothing)
- checked gemini (gemini is working fine)
- tried graphite in an incognito tab (didnt work)
- tried graphite in another browser (i use firefox, so i tried chrome and BING 🤮)

 (evan zhou if you're seeing this im sorry for ghosting you earlier)

**Comment by EvanZhouDev** [comment]
I believe I have fixed this. Please try again. Google appears to have changed their API support a little bit, and that threw things off.

**Comment by chamoysans** [comment]
works now!!!!! thanks
